autoclip: false
autoimport: true
cliptimeout: 45
exportkeys: false
nopager: false
notifications: true
parsing: true
path: /Users/sasan/.local/share/gopass/stores/root
safecontent: false
mounts:
    Password: /Users/sasan/.local/share/gopass/stores/Password
