theme = "dark_plus"

[editor]
auto-completion                    = true
auto-format                        = true
auto-info                          = true
auto-save                          = true
bufferline                         = "always"
color-modes                        = true
completion-replace                 = true
completion-timeout                 = 5
completion-trigger-len             = 1
cursorcolumn                       = true
cursorline                         = true
default-line-ending                = "lf"
idle-timeout                       = 5
indent-heuristic                   = "hybrid"
insert-final-newline               = true
jump-label-alphabet                = "asdfghjklweruio"
line-number                        = "relative"
middle-click-paste                 = true
mouse                              = true
preview-completion-insert          = true
# rulers                             = [80]
scroll-lines                       = 5
scrolloff                          = 5
text-width                         = 80
true-color                         = true
undercurl                          = true
end-of-line-diagnostics            = "hint"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"
# Minimum severity to show a diagnostic on other lines:
# other-lines = "error"


[editor.file-picker]
hidden                             = false
follow-symlinks                    = true
deduplicate-links                  = true
parents                            = true
ignore                             = true
git-ignore                         = true
git-global                         = true
git-exclude                        = true
max-depth                          = 5

[editor.soft-wrap]
enable = true

#[editor.persistence]
#old-files = true
#commands = true
#search = true
#clipboard = true

[editor.gutters]
layout                             = ["line-numbers","diagnostics","diff"]

[editor.indent-guides]
character                          = "|"
render                             = true
skip-levels                        = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.statusline]
left                               = ["mode","spinner","version-control", "file-name","file-modification-indicator",]
center                             = ["workspace-diagnostics","spacer"]
right                              = ["primary-selection-length","spacer","register","spacer","position","separator","total-line-numbers","separator","position-percentage","file-type","file-encoding","file-line-ending"]
separator                          = ":"
mode.insert                        = "INSERT"
mode.normal                        = "NORMAL"
mode.select                        = "SELECT"

[editor.lsp]
auto-signature-help                = true
display-inlay-hints                = true
display-messages                   = true
display-signature-help-docs        = true
enable                             = true
goto-reference-include-declaration = true
snippets                           = true

###################
# KEYBINDINGS     #
###################

[keys.normal]
# Quick iteration on config changes
C-o = ":config-open"
#C-r = ":config-reload"
C-r = "redo"

# Some nice Helix stuff
# C-h = "select_prev_sibling"
# C-j = "shrink_selection"
# C-k = "expand_selection"
# C-l = "select_next_sibling"
esc      = ["collapse_selection", "keep_primary_selection"]
ret      = ["align_view_center", "goto_word"]
C-tab      = [":bn"]
C-S-tab    = [":bp"]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
S        = ["surround_add"]
# h        = ["move_char_left", "align_view_center"]
# j        = ["move_line_down","align_view_center"]
# k        = ["move_line_up","align_view_center"]
# l        = ["move_char_right", "align_view_center"]
C-k      = ["extend_to_line_bounds","delete_selection", "move_line_up","paste_before"]
C-j      = ["extend_to_line_bounds","delete_selection", "move_line_down","paste_before"]
C-b      = ["goto_line_start"]
C-e      = ["goto_line_end"]
# "*"      = ["move_prev_word_start", "move_next_word_end", "search_selection"]
A-h      = ["extend_parent_node_start"]
A-l      = ["extend_parent_node_end"]

# Personal preference
o = ["open_below", "insert_mode"]
O = ["open_above", "insert_mode"]

# Muscle memory
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
"%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
# S = "surround_add" # Would be nice to be able to do something after this but it isn't chainable

# Clipboards over registers ye ye
x = "delete_selection"
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
# Would be nice to add ya and yi, but the surround commands can't be chained
Y = ["extend_to_line_end", "yank_main_selection_to_clipboard", "collapse_selection"]

# Uncanny valley stuff, this makes w and b behave as they do Vim
# w = ["move_next_word_start", "move_char_right", "collapse_selection"]
W = ["move_next_long_word_start", "move_char_right", "collapse_selection"]
# e = ["move_next_word_end", "collapse_selection"]
E = ["move_next_long_word_end", "collapse_selection"]
# b = ["move_prev_word_start", "collapse_selection"]
B = ["move_prev_long_word_start", "collapse_selection"]

# If you want to keep the selection-while-moving behaviour of Helix, this two lines will help a lot,
# especially if you find having text remain selected while you have switched to insert or append mode
#
# There is no real difference if you have overridden the commands bound to 'w', 'e' and 'b' like above
# But if you really want to get familiar with the Helix way of selecting-while-moving, comment the
# bindings for 'w', 'e', and 'b' out and leave the bindings for 'i' and 'a' active below. A world of difference!
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]

# Undoing the 'd' + motion commands restores the selection which is annoying
u = ["undo", "collapse_selection"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
# esc = ["collapse_selection", "keep_primary_selection"]

# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

# Make j and k behave as they do Vim when soft-wrap is enabled
j = "move_line_down"
k = "move_line_up"

# Extend and select commands that expect a manual input can't be chained
# I've kept d[X] commands here because it's better to at least have the stuff you want to delete
# selected so that it's just a keystroke away to delete
[keys.normal.space.t]
a        = ":toggle-option auto-completion"
s        = ":toggle-option auto-save"
f        = ":toggle-option auto-format"
h        = ":toggle-option lsp.display-inlay-hints"
l        = ":toggle-option lsp.enable"

[keys.normal.space.C]
l        = ":o ~/.config/helix/languages.toml"
o        = ":config-open"
r        = [":w", ":config-reload",":reload-all"]

[keys.normal.space]
","      = ["save_selection", "goto_line_end", ":append-output echo ','", "collapse_selection", "delete_selection", "jump_backward"]
";"      = ["save_selection", "goto_line_end", ":append-output echo ';'", "collapse_selection", "delete_selection", "jump_backward"]

[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
t = ["extend_till_char"]
s = ["surround_delete"]
i = ["select_textobject_inner"]
a = ["select_textobject_around"]
j = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
down = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
k = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
up = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
G = ["select_mode", "extend_to_line_bounds", "goto_last_line", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "delete_selection"]
W = ["move_next_long_word_start", "yank_main_selection_to_clipboard", "delete_selection"]
g = { g = ["select_mode", "extend_to_line_bounds", "goto_file_start", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"] }

[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]
j = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
down = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
k = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
up = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
G = ["select_mode", "extend_to_line_bounds", "goto_last_line", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
W = ["move_next_long_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
g = { g = ["select_mode", "extend_to_line_bounds", "goto_file_start", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"] }

[keys.insert]
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "normal_mode"]
A-j      = ["normal_mode","extend_to_line_bounds","delete_selection", "move_line_down","paste_before", "insert_mode"]
A-k      = ["normal_mode","extend_to_line_bounds","delete_selection", "move_line_up","paste_before", "insert_mode"]
C-b      = ["insert_at_line_start","align_view_center"]
C-e      = ["insert_at_line_end","align_view_center"]
C-h      = ["move_char_left","align_view_center"]
C-j      = ["move_line_down","align_view_center"]
C-k      = ["move_line_up","align_view_center"]
C-l      = ["move_char_right","align_view_center"]
S-tab    = "move_parent_node_start"


[keys.select]
# Muscle memory
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
"%" = "match_brackets"
S = "surround_add" # Basically 99% of what I use vim-surround for
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
# Visual-mode specific muscle memory
i = "select_textobject_inner"
a = "select_textobject_around"

# Some extra binds to allow us to insert/append in select mode because it's nice with multiple cursors
#tab = ["insert_mode", "collapse_selection"] # tab is read by most terminal editors as "C-i"
C-a = ["append_mode", "collapse_selection"]

# Make selecting lines in visual mode behave sensibly
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

# Clipboards over registers ye ye
d = ["yank_main_selection_to_clipboard", "delete_selection"]
x = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
p = "replace_selections_with_clipboard" # No life without this
P = "paste_clipboard_before"

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
pageup   = ["half_page_up"]
pagedown = ["half_page_down"]
"C-u"    = ["half_page_up"]
"C-d"    = ["half_page_down"]
# esc      = ["collapse_selection", "normal_mode"]
c        = ["trim_selections", "change_selection"]
";"      = ["flip_selections"]
","      = ["repeat_last_motion"]

[keys.select."]"]
"]"      = ["goto_prev_paragraph"]

[keys.select."["]
"["      = ["goto_next_paragraph"]
